NoSuchMethodError: GroovyClassLoader.parseClass (#2)
* NoSuchMethodError: GroovyClassLoader.parseClass

As said in https://issues.jenkins-ci.org/browse/JENKINS-36434, the method parseClass(InputStream in) has been removed.
Use of the deprecated function : parseClass(InputStream in, String fileName).

* Customized commit message

add author to commit message.

* Revert "Customized commit message"

This reverts commit fbd505acaa77775bbee101501073c5bfe9137abc.